"""Protocol for tags business-logic service."""

from typing import Protocol, runtime_checkable, Dict, List


@runtime_checkable
class TagsService(Protocol):
    """Protocol for tags business-logic service."""

    async def estimate_tags(
        self,
        analysis_type: str = "nonsense",
    ) -> Dict: ...

    async def delete_empty_tags(self) -> Dict: ...

    async def bulk_delete_tags(self, tag_ids: List[int]) -> Dict: ...

    async def remove_tags_from_saved_analyses(self, tag_ids: List[int]) -> Dict: ...

    async def get_saved_analysis(self, entity_type: str) -> dict: ...

    async def load_saved_analysis(self, entity_type: str) -> dict: ...

    async def delete_saved_analysis(self, entity_type: str) -> None: ...

    async def mark_group_processed(self, entity_type: str, group_index: int) -> None: ...

    async def save_similarity_analysis(self, result: Dict) -> None: ...

    async def save_nonsense_analysis(self, result: Dict) -> None: ...

    async def get_saved_nonsense_analysis(self) -> dict: ...

    async def load_saved_nonsense_analysis(self) -> dict: ...

    async def delete_saved_nonsense_analysis(self) -> None: ...

    async def save_doctype_matches(self, result: Dict) -> None: ...

    async def get_saved_correspondent_matches(self) -> dict: ...

    async def load_saved_correspondent_matches(self) -> dict: ...

    async def delete_saved_correspondent_matches(self) -> None: ...

    async def save_correspondent_matches(self, result: Dict) -> None: ...

    async def get_saved_doctype_matches(self) -> dict: ...

    async def load_saved_doctype_matches(self) -> dict: ...

    async def delete_saved_doctype_matches(self) -> None: ...
