"""Protocol for document types business-logic service."""

from typing import Dict, Optional, Protocol, runtime_checkable


@runtime_checkable
class DocumentTypesService(Protocol):
    """Protocol for document types business-logic service."""

    async def estimate_document_types(self) -> Dict: ...

    async def save_similarity_analysis(self, result: Dict) -> None: ...

    async def delete_empty_document_types(self) -> Dict: ...

    async def get_saved_analysis(self) -> dict: ...

    async def load_saved_analysis(self) -> Optional[dict]: ...

    async def delete_saved_analysis(self) -> None: ...

    async def mark_group_processed(self, group_index: int) -> None: ...
