"""Protocol for auth service."""

from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class AuthService(Protocol):
    """Protocol for auth service."""

    async def get_or_create_auth_config(self) -> dict: ...

    async def set_password(self, password: str) -> None: ...

    async def validate_password(self, password: str) -> bool: ...

    async def change_password(self, current_password: str, new_password: str) -> bool: ...

    def create_session(self) -> str: ...

    def revoke_session(self, token: str) -> None: ...

    def is_session_valid(self, token: Optional[str]) -> bool: ...

    def is_auth_disabled(self) -> bool: ...
