"""Protocol for Paperless-ngx API client."""

from typing import Protocol, runtime_checkable, Optional, List, Dict


@runtime_checkable
class PaperlessClient(Protocol):
    """Protocol for Paperless-ngx API client."""

    base_url: str

    async def test_connection(self) -> bool: ...

    async def get_correspondents(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_correspondents_with_counts(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_tags(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_tags_with_counts(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_document_types(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_document_types_with_counts(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_storage_paths(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_custom_fields(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_document(self, document_id: int) -> Optional[Dict]: ...

    async def get_document_count(
        self,
        tag_id: int | None = None,
        tags_id_all: List[int] | None = None,
        tags_id_none: List[int] | None = None,
    ) -> int: ...

    async def bulk_update_documents(
        self,
        document_ids: List[int],
        correspondent_id: int | None = None,
        add_tags: List[int] | None = None,
        remove_tags: List[int] | None = None,
        document_type_id: int | None = None,
    ) -> Dict: ...

    async def get_or_create_tag(self, name: str) -> Dict: ...

    async def get_or_create_correspondent(self, name: str) -> Dict: ...

    async def get_document_preview_image(self, document_id: int) -> bytes: ...

    async def get_document_thumbnail_bytes(self, document_id: int) -> bytes: ...

    async def download_document_file(self, document_id: int) -> bytes: ...

    async def update_document(self, document_id: int, data: Dict) -> Dict: ...

    async def get_documents(
        self,
        correspondent_id: int | None = None,
        tag_id: int | None = None,
        document_type_id: int | None = None,
        query: str | None = None,
        page_size: int = 1000,
    ) -> List[Dict]: ...

    async def get_documents_by_correspondent(self, correspondent_id: int) -> List[Dict]: ...

    async def get_documents_by_tag(self, tag_id: int) -> List[Dict]: ...

    async def get_documents_by_document_type(self, doc_type_id: int) -> List[Dict]: ...

    async def delete_correspondent(self, correspondent_id: int) -> None: ...

    async def delete_tag(self, tag_id: int) -> None: ...

    async def delete_tags_bulk(self, tag_ids: List[int]) -> dict: ...

    async def delete_document_type(self, doc_type_id: int) -> None: ...

    async def delete_document(self, document_id: int) -> None: ...

    async def create_correspondent(self, name: str) -> Dict: ...

    async def create_tag(self, name: str) -> Dict: ...

    async def add_tag_to_document(self, document_id: int, tag_id: int) -> Dict: ...

    async def remove_tag_from_document(self, document_id: int, tag_id: int) -> Dict: ...

    async def update_correspondent(self, correspondent_id: int, data: Dict) -> Dict: ...

    async def update_tag(self, tag_id: int, data: Dict) -> Dict: ...

    async def update_document_type(self, doc_type_id: int, data: Dict) -> Dict: ...

    async def get_document_previews(
        self,
        correspondent_id: int | None = None,
        tag_id: int | None = None,
        document_type_id: int | None = None,
        limit: int = 5,
    ) -> List[Dict]: ...

    async def upload_document(
        self,
        file_bytes: bytes,
        filename: str,
        correspondent_id: int | None = None,
        document_type_id: int | None = None,
        tag_ids: List[int] | None = None,
    ) -> str: ...

    def get_thumbnail_url(self, document_id: int) -> str: ...

    def get_document_view_url(self, document_id: int) -> str: ...
