"""Protocol for Paperless-ngx API client."""

from typing import Protocol, runtime_checkable, Optional, List, Dict


@runtime_checkable
class PaperlessClient(Protocol):
    """Protocol for Paperless-ngx API client."""

    async def test_connection(self) -> bool: ...

    async def get_correspondents(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_tags(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_document_types(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_storage_paths(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_custom_fields(self, use_cache: bool = True) -> List[Dict]: ...

    async def get_document(self, document_id: int) -> Optional[Dict]: ...

    async def get_document_count(self, **kwargs) -> int: ...

    async def bulk_update_documents(self, **kwargs) -> None: ...

    async def get_or_create_tag(self, name: str) -> Dict: ...

    async def get_document_preview_image(self, document_id: int) -> bytes: ...

    async def get_document_thumbnail_bytes(self, document_id: int) -> bytes: ...

    async def download_document_file(self, document_id: int) -> bytes: ...

    async def update_document(self, document_id: int, data: Dict) -> Dict: ...

    async def get_documents(self, **kwargs) -> List[Dict]: ...

    async def get_documents_by_correspondent(self, correspondent_id: int) -> List[Dict]: ...

    async def delete_correspondent(self, correspondent_id: int) -> bool: ...

    async def delete_tag(self, tag_id: int) -> bool: ...

    async def delete_document_type(self, document_type_id: int) -> bool: ...

    async def post(self, endpoint: str, **kwargs) -> Optional[Dict]: ...

    async def get(self, endpoint: str, **kwargs) -> Optional[Dict]: ...

    async def _request(self, method: str, endpoint: str, **kwargs) -> Optional[Dict]: ...