#!/bin/bash
# Setup script for Podman devcontainer
# This script creates a .env file with your host UID/GID for proper permission mapping
# It is automatically run by VS Code via initializeCommand in devcontainer.json

echo script
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
RUNTIME_ENV_FILE="$SCRIPT_DIR/../.env"

touch "$RUNTIME_ENV_FILE"

# Get host UID and GID
HOST_UID=$(id -u)
HOST_GID=$(id -g)

# Check if running as root (UID=0) - this usually indicates a problem
if [ "$HOST_UID" = "0" ] || [ "$HOST_GID" = "0" ]; then
    echo "ERROR: Detected UID/GID of 0 (root)"
    echo ""
    echo "This usually happens when VS Code is running as Administrator."
    echo ""
    echo "On Windows: Launch VS Code from a bash shell (Git Bash, WSL, etc.) instead of the Start Menu:"
    echo "  1. Open a bash shell (not as Administrator)"
    echo "  2. Navigate to your project: cd /c/Projects/MyProject"
    echo "  3. Launch VS Code: code ."
    echo ""
    echo "On Linux/Mac: Do not run VS Code with sudo or as root user."
    echo ""
    echo "See README.md for more details."
    exit 1
fi

# Check if .env already exists with correct values
if [ ! -f "$ENV_FILE" ]; then
    touch "$ENV_FILE"
fi

CURRENT_UID=$(grep "^USER_UID=" "$ENV_FILE" 2>/dev/null | cut -d= -f2)
CURRENT_GID=$(grep "^USER_GID=" "$ENV_FILE" 2>/dev/null | cut -d= -f2)

if [ "$CURRENT_UID" = "$HOST_UID" ] && [ "$CURRENT_GID" = "$HOST_GID" ]; then
    echo "User permissions already configured (UID: $HOST_UID, GID: $HOST_GID)"
else
    echo "Configuring container user permissions for rootless Podman..."
    echo "   Host UID: $HOST_UID"
    echo "   Host GID: $HOST_GID"

    # Create or update .env file
    cat > "$ENV_FILE" << EOF
# Auto-generated by setup-podman.sh
# User ID mapping for rootless Podman compatibility
USER_UID=$HOST_UID
USER_GID=$HOST_GID
EOF
    echo "Created .devcontainer/.env with your host UID/GID"
    echo "Container will be built with matching user permissions"
fi
