"""Protocol for cloud import service."""

from typing import Protocol, runtime_checkable, Any, Dict, List

# Import PaperlessClient — cross-service, use package-level
from app.services.paperless import PaperlessClient


@runtime_checkable
class CloudImportService(Protocol):
    """Protocol for cloud import service."""

    async def sync_source(self, source: Any, pl_client: PaperlessClient, db: Any) -> Dict: ...

    async def test_connection(self, source: Any) -> Dict: ...

    async def list_files(self, source: Any) -> List[Dict]: ...

    async def list_sources(self) -> list: ...

    async def create_source(self, data: dict) -> dict: ...

    async def update_source(self, source_id: int, data: dict) -> dict: ...

    async def delete_source(self, source_id: int) -> None: ...

    async def get_source(self, source_id: int) -> Any: ...

    async def sync_source_now(self, source_id: int, client: Any) -> dict: ...

    async def list_folders(self, source: Any, path: str = "/") -> List[Dict]: ...

    async def get_import_log(self, source_id: int = None, limit: int = 100) -> list: ...

    async def clear_import_log(self, source_id: int = None) -> None: ...

    def get_sync_status_dict(self) -> dict: ...

    async def start_sync_daemon(self, config_svc: Any) -> dict: ...

    async def stop_sync_daemon(self, config_svc: Any) -> dict: ...

    async def get_paperless_tags(self, client: Any) -> list: ...

    async def get_paperless_correspondents(self, client: Any) -> list: ...

    async def get_paperless_document_types(self, client: Any) -> list: ...