"""Protocol for document classifier service."""

from typing import Protocol, runtime_checkable, Any, Dict, List

from app.services.paperless import PaperlessClient


@runtime_checkable
class DocumentClassifierService(Protocol):
    """Protocol for document classifier service."""

    async def classify_document(self, document_id: int) -> Any: ...

    async def classify_document_auto(self, document_id: int, mode: str = "review") -> Dict[str, Any]: ...

    async def benchmark_document(self, document_id: int, slots: List[tuple]) -> Dict: ...

    async def apply_classification(self, document_id: int, classification: Dict) -> Dict: ...

    async def get_config(self) -> Any: ...

    async def get_config_response(self, active_provider: str, active_model: str) -> Dict[str, Any]: ...

    async def save_config(self, updates: Dict[str, Any]) -> Any: ...

    async def get_storage_profiles(self) -> List[Any]: ...

    async def save_storage_profile(self, data: Dict[str, Any]) -> Any: ...

    async def get_custom_field_mappings(self) -> List[Any]: ...

    async def save_custom_field_mapping(self, data: Dict[str, Any]) -> Any: ...

    async def get_stats(self, client: PaperlessClient) -> Dict[str, Any]: ...

    async def get_next_unclassified(self, after_id: int, client: PaperlessClient) -> Dict[str, Any]: ...

    async def get_storage_path_profiles_merged(self, client: PaperlessClient) -> List[Dict[str, Any]]: ...

    async def get_custom_field_mappings_merged(self, client: PaperlessClient) -> List[Dict[str, Any]]: ...

    async def get_history(self, limit: int = 50) -> List[Dict[str, Any]]: ...

    async def get_tag_stats(self) -> Dict[str, Any]: ...

    async def get_review_queue(self) -> List[Dict[str, Any]]: ...

    async def approve_review(self, entry_id: int, document_id: int, classification: Dict[str, Any]) -> Dict[str, Any]: ...

    async def dismiss_review(self, entry_id: int) -> Dict[str, str]: ...

    async def get_tag_ideas(self) -> List[Dict[str, Any]]: ...

    async def get_tag_ideas_stats(self) -> Dict[str, Any]: ...

    async def approve_tag_idea(self, entry_id: int, tag_name: str, client: PaperlessClient) -> Dict[str, Any]: ...

    async def dismiss_tag_idea(self, entry_id: int, tag_name: str) -> Dict[str, Any]: ...

    async def approve_all_tag_ideas(self, entry_id: int, client: PaperlessClient) -> Dict[str, Any]: ...

    async def bulk_approve_tag_idea(self, tag_name: str, client: PaperlessClient) -> Dict[str, Any]: ...

    async def bulk_dismiss_tag_idea(self, tag_name: str) -> Dict[str, Any]: ...

    async def assign_existing_tag(self, entry_id: int, tag_name: str, client: PaperlessClient) -> Dict[str, Any]: ...
