"""Protocol for document classifier service."""

from typing import Protocol, runtime_checkable, Optional, List, Dict, Any


@runtime_checkable
class DocumentClassifierService(Protocol):
    """Protocol for document classifier service."""

    async def classify_document(self, document_id: int) -> Any: ...

    async def classify_document_auto(self, document_id: int, mode: str = "review") -> Dict[str, Any]: ...

    async def benchmark_document(self, document_id: int, slots: List[tuple]) -> Dict: ...

    async def apply_classification(self, document_id: int, classification: Dict) -> Dict: ...

    async def get_config(self) -> Any: ...

    async def save_config(self, updates: Dict[str, Any]) -> Any: ...

    async def get_storage_profiles(self) -> List[Any]: ...

    async def save_storage_profile(self, data: Dict[str, Any]) -> Any: ...

    async def get_custom_field_mappings(self) -> List[Any]: ...

    async def save_custom_field_mapping(self, data: Dict[str, Any]) -> Any: ...
